### ISSUE TITLE
g++ warns in float_to_useconds: "no return statement"

### ISSUE THREAD

**Issue by dksmiffs** [ajdehel/udp-broadcast#3]
https://github.com/ajdehel/udp-broadcast/blob/de3e0a963e8119a2ca7ab8df1f4fb42eee2cfd87/cpp/src/utils.hpp#L17

This function definitely looks like it needs a return statement.  I'm using g++ 8.3.1 on Lubuntu 18.04 LTS.

**Comment by ajdehel** [comment]
I cannot believe I missed that; thank you. it's fixed in 64ddf1a
