### ISSUE TITLE
halfway torndown state?  Suggestions welcome...

### ISSUE THREAD

**Issue by dksmiffs** [ajdehel/udp-broadcast#4]
https://github.com/ajdehel/udp-broadcast/blob/64ddf1ab4655ea6d3c7737fea72c376b7eaf9e6e/example.py#L29

See the attached image.  Any suggestions?
![2020-04-13-165335_1440x900_scrot](https://user-images.githubusercontent.com/1774172/79166472-dc2bed00-7daa-11ea-985a-e6477a3afd1c.png)

**Comment by dksmiffs** [comment]
- `ip addr show` shows more output than I remember previously
- BUT, `ip netns` shows nothing
- also, teardown instructions DID work, but followed up with another setup gave the above problem

**Comment by dksmiffs** [comment]
This problem is repeatable on my machine.  Sequence:
1. setup (successful)
1. run (successful)
1. teardown (reports success, but there's extra stuff in `ip addr show`)
1. setup (FAILS, as in above screenshot)
1. reboot (afterwards, `ip addr show` looks clean)
1. setup (successful)... (sequence repeats with this problem as above)

**Comment by ajdehel** [comment]
this should be fixed in branch 'issue4'

**Comment by dksmiffs** [comment]
verified fix
